In [1]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

np.set_printoptions(precision=4)

<center>
    
# Aprendizagem de Máquina (ES456/2018-2)
## Lista de exercícios 1
### 2018-09-22
    
</center>

1) Utilizando a base de dados Iris, disponível no link abaixo, e a linguagem de programação de sua preferência, calcule para cada classe:
<br />
a) O vetor médio
<br />
b) O vetor de desvio padrão para cada característica da base de dados
<br />
c) O vetor máximo para cada característica da base de dados
<br />
d) O vetor mínimo para cada característica da base de dados
<br />
e) A matriz de dispersão
<br />
f) A matriz de covariância
<br />
g) A matriz de correlação
<br />
h) As duas componentes principais de maior magnitude dos dados
<br />
i) A projeção dos dados nas duas maiores componentes principais

In [2]:
# iris-setosa -> 0
# iris-versicolor -> 1
# iris-virginica -> 2

iris = datasets.load_iris()
iris_features = iris.data[:, :4]
iris_target = iris.target
classes_number = len(set(iris_target))

def class_name(class_):
    if class_ == 0: return 'iris-setosa'
    if class_ == 1: return 'iris-versicolor'
    if class_ == 2: return 'iris-virginica'

def print_answer(question, answer):
    print(f"Resposta {question}:\n{answer}")

In [3]:
def mean(array):
    return sum(array)/len(array)

def column_vec(func, matrix):
    return [func(matrix[:,i]) for i in range(len(matrix[0]))]

print('1a)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(mean, iris_features[np.where(iris_target == i)]))

1a)
iris-setosa
[5.005999999999999, 3.4180000000000006, 1.464, 0.2439999999999999]
iris-versicolor
[5.936, 2.7700000000000005, 4.26, 1.3259999999999998]
iris-virginica
[6.587999999999998, 2.9739999999999998, 5.552, 2.026]


In [4]:
def standard_deviation(array):
    if len(array) == 0: return 0.0
    _mean = mean(array)
    sq_diff_sum = sum([(number-_mean)**2 for number in array])
    return (sq_diff_sum/(len(array)-1))**0.5

print('1b)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(standard_deviation, iris_features[np.where(iris_target == i)]))

1b)
iris-setosa
[0.3524896872134512, 0.38102439795469095, 0.1735111594364455, 0.10720950308167837]
iris-versicolor
[0.5161711470638635, 0.3137983233784114, 0.46991097723995806, 0.197752680004544]
iris-virginica
[0.635879593274432, 0.3224966381726376, 0.5518946956639835, 0.27465005563666733]


In [5]:
print('1c)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(max, iris_features[np.where(iris_target == i)]))

1c)
iris-setosa
[5.8, 4.4, 1.9, 0.6]
iris-versicolor
[7.0, 3.4, 5.1, 1.8]
iris-virginica
[7.9, 3.8, 6.9, 2.5]


In [6]:
print('1d)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(min, iris_features[np.where(iris_target == i)]))

1d)
iris-setosa
[4.3, 2.3, 1.0, 0.1]
iris-versicolor
[4.9, 2.0, 3.0, 1.0]
iris-virginica
[4.9, 2.2, 4.5, 1.4]


In [7]:
def dispersion_matrix(matrix):
    return (matrix - column_vec(mean, matrix)).T.dot((matrix - column_vec(mean, matrix)))

print('1e)')
for i in range(classes_number):
    print(class_name(i))
    print(dispersion_matrix(iris_features[np.where(iris_target == i)]))

1e)
iris-setosa
[[6.0882 4.9146 0.7908 0.5168]
 [4.9146 7.1138 0.5724 0.5604]
 [0.7908 0.5724 1.4752 0.2792]
 [0.5168 0.5604 0.2792 0.5632]]
iris-versicolor
[[13.0552  4.174   8.962   2.7332]
 [ 4.174   4.825   4.05    2.019 ]
 [ 8.962   4.05   10.82    3.582 ]
 [ 2.7332  2.019   3.582   1.9162]]
iris-virginica
[[19.8128  4.5944 14.8612  2.4056]
 [ 4.5944  5.0962  3.4976  2.3338]
 [14.8612  3.4976 14.9248  2.3924]
 [ 2.4056  2.3338  2.3924  3.6962]]


In [8]:
def covariance(x1, x2):
    return mean(x1*x2) - mean(x1)*mean(x2)

def cov_matrix(matrix):
    columns_num = matrix.shape[1]
    result = np.zeros((columns_num, columns_num))
    
    for i in range(columns_num):
        result[i][i] = standard_deviation(matrix[:,i])**2
        for j in range(i+1, columns_num):
            result[i][j] = covariance(matrix[:,i], matrix[:,j])
            result[j][i] = result[i][j]
            
    return result

print('1f)')
for i in range(classes_number):
    print(class_name(i))
    print((cov_matrix(iris_features[np.where(iris_target == i)])))

1f)
iris-setosa
[[0.1242 0.0983 0.0158 0.0103]
 [0.0983 0.1452 0.0114 0.0112]
 [0.0158 0.0114 0.0301 0.0056]
 [0.0103 0.0112 0.0056 0.0115]]
iris-versicolor
[[0.2664 0.0835 0.1792 0.0547]
 [0.0835 0.0985 0.081  0.0404]
 [0.1792 0.081  0.2208 0.0716]
 [0.0547 0.0404 0.0716 0.0391]]
iris-virginica
[[0.4043 0.0919 0.2972 0.0481]
 [0.0919 0.104  0.07   0.0467]
 [0.2972 0.07   0.3046 0.0478]
 [0.0481 0.0467 0.0478 0.0754]]


In [9]:
# alternative method to calculate dispersion matrix
def dispersion_matrix2(matrix):
    return cov_matrix(matrix)*(len(matrix[:, 0])-1)

# alternative method to calculate covariance matrix
def cov_matrix2(matrix):
    return dispersion_matrix2(matrix)/(len(matrix[:, 0]) - 1)

In [10]:
def inverse_std_dev_matrix(matrix):
    columns_num = matrix.shape[1]
    result = np.zeros((columns_num, columns_num))
    
    for i in range(columns_num):
        result[i][i] = 1/(standard_deviation(matrix[:,i])**2)
        for j in range(i+1, columns_num):
            result[i][j] = 1/(standard_deviation(matrix[:,i]) * standard_deviation(matrix[:,j]))
            result[j][i] = result[i][j]
    
    return result
            
def cor_matrix(matrix):
    return cov_matrix(matrix) * inverse_std_dev_matrix(matrix)

print('1g)')
for i in range(classes_number):
    print(class_name(i))
    print(cor_matrix(iris_features[np.where(iris_target == i)]))

1g)
iris-setosa
[[1.     0.7318 0.2586 0.2735]
 [0.7318 1.     0.1732 0.2744]
 [0.2586 0.1732 1.     0.3002]
 [0.2735 0.2744 0.3002 1.    ]]
iris-versicolor
[[1.     0.5154 0.739  0.5355]
 [0.5154 1.     0.5493 0.6507]
 [0.739  0.5493 1.     0.7709]
 [0.5355 0.6507 0.7709 1.    ]]
iris-virginica
[[1.     0.4481 0.8469 0.2755]
 [0.4481 1.     0.393  0.527 ]
 [0.8469 0.393  1.     0.3157]
 [0.2755 0.527  0.3157 1.    ]]


In [11]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix(iris_features))

print_answer('1h)', eigenvectors[:, 0:2])

Resposta 1h):
[[ 0.3606 -0.6657]
 [-0.082  -0.7203]
 [ 0.8575  0.1809]
 [ 0.3578  0.0723]]


In [12]:
print_answer('1i)', iris_features.dot(eigenvectors[:, :2]))

Resposta 1i):
[[ 2.8239 -5.6486]
 [ 2.7928 -5.1553]
 [ 2.6185 -5.1843]
 [ 2.7621 -5.0095]
 [ 2.7796 -5.6541]
 [ 3.228  -6.0678]
 [ 2.6876 -5.2365]
 [ 2.8818 -5.4919]
 [ 2.6207 -4.7504]
 [ 2.8345 -5.2165]
 [ 3.0014 -5.9743]
 [ 2.8954 -5.3407]
 [ 2.7209 -5.096 ]
 [ 2.2834 -4.8174]
 [ 2.8638 -6.511 ]
 [ 3.1237 -6.6638]
 [ 2.885  -6.1401]
 [ 2.8596 -5.6414]
 [ 3.3086 -6.2027]
 [ 2.9208 -5.8394]
 [ 3.1975 -5.7221]
 [ 2.9648 -5.7602]
 [ 2.2924 -5.4602]
 [ 3.2048 -5.4286]
 [ 3.1526 -5.2864]
 [ 3.0003 -5.1857]
 [ 3.0391 -5.4594]
 [ 2.9457 -5.6971]
 [ 2.8681 -5.6432]
 [ 2.8757 -5.1301]
 [ 2.92   -5.1246]
 [ 3.0975 -5.7438]
 [ 2.8607 -6.1365]
 [ 2.9107 -6.4191]
 [ 2.8345 -5.2165]
 [ 2.6409 -5.4021]
 [ 2.8823 -5.933 ]
 [ 2.8345 -5.2165]
 [ 2.5267 -4.8406]
 [ 2.9178 -5.5585]
 [ 2.7378 -5.5929]
 [ 2.656  -4.3957]
 [ 2.5103 -4.9846]
 [ 3.1024 -5.517 ]
 [ 3.2996 -5.7598]
 [ 2.7925 -5.0815]
 [ 2.9708 -5.8285]
 [ 2.6682 -5.0997]
 [ 2.9653 -5.9078]
 [ 2.8042 -5.438 ]
 [ 6.7925 -6.0138]
 [ 6.4405 -5.6433

2) Implemente o algoritmo do k-means na linguagem de programação de sua preferência e inicializeeste algoritmo com k=3 centros c1=[5.1,3.5,1.4,0.2], c2=[4.9,3.0,1.4,0.2], c3=[4.7,3.2,1.3,0.2].
<br />
    a) Após a convergência, qual o valor dos centros?
    <br />
    b) Qual o centro mais próximo do centro da classe “Iris-setosa”
    <br />
    c) Qual o centro mais próximo do centro da classe “Iris-versicolor”
    <br />
    d) Qual o centro mais próximo do centro da classe “Iris-virginica”

In [13]:
def dist(a, b):
    return np.linalg.norm(np.array(a) - np.array(b), axis=1)

def kmeans(matrix, k, centroids):
    current_centroids = np.array(centroids)
    previous_centroids = np.zeros(current_centroids.shape)

    error = dist(current_centroids, previous_centroids)
    nearest_clusters = np.zeros(len(matrix))
    
    while sum(error) != 0:
        for i in range(len(matrix)):
            distances = dist(matrix[i], current_centroids)
            nearest_clusters[i] = np.argmin(distances)

            previous_centroids = current_centroids.copy()

        for i in range(k):
            current_centroids[i] = np.mean(matrix[np.where(nearest_clusters == i)], axis=0)

        error = dist(current_centroids, previous_centroids)
    return (nearest_clusters, current_centroids)

def get_center(features, target):
    target_set = set(target)
    return np.array([np.mean(features[np.where(target == i)], 0) for i in range(len(target_set))])

center1 = [5.1, 3.5, 1.4, 0.2]
center2 = [4.9, 3.0, 1.4, 0.2]
center3 = [4.7, 3.2, 1.3, 0.2]

closest_cluster, kmeans_centers = kmeans(iris_features, 3, [center1, center2, center3])

centers = get_center(iris_features, iris_target)

print_answer('2a)', kmeans_centers)

print_answer('2b)', np.argmin(dist(centers[0], kmeans_centers)))
print_answer('2c)', np.argmin(dist(centers[1], kmeans_centers)))
print_answer('2d)', np.argmin(dist(centers[2], kmeans_centers)))

Resposta 2a):
[[6.8538 3.0769 5.7154 2.0538]
 [5.8836 2.741  4.3885 1.4344]
 [5.006  3.418  1.464  0.244 ]]
Resposta 2b):
2
Resposta 2c):
1
Resposta 2d):
0


In [14]:
kmeans_class = closest_cluster.copy()
kmeans_class[np.where(closest_cluster == 2)] = 0
kmeans_class[np.where(closest_cluster == 1)] = 1
kmeans_class[np.where(closest_cluster == 0)] = 2

error = sum([1 if iris_target[i] != kmeans_class[i] else 0 for i in range(len(iris_target))])/len(iris_target)

print(f'Error: {error*100:.2f}%')

Error: 11.33%


3) Implemente o algoritmo do KNN na linguagem de programação de sua preferência.

In [15]:
import collections

def get_neighbors(matrix, element, k):
    dist = lambda a, b: np.linalg.norm(a-b, axis=0)
    near_elements = []
    
    for i, other_element in enumerate(matrix):
        distance = dist(element[0:-1], other_element[0:-1])
        near_elements.append((other_element[-1], distance))
    
    near_elements.sort(key = lambda x: x[1])
    
    # return distances removing 1st element that is the element itself
    return np.array([near_elements[i][0] for i in range(1, k+1)])

def class_from_neighbors(neighbors):
    return max(collections.Counter(neighbors))

def knn(train, test, k):
    classes = []
    correct = 0
    for i, element in enumerate(test):
        neighbors = get_neighbors(train, element, k)
        class_ = class_from_neighbors(neighbors)
        classes.append(class_)
        # print(f'> Prediction = {class_}, Actual = {element[-1]}')
        
        if class_ == element[-1]: correct += 1
            
    print(f'Error = {(1 - correct/len(test))*100:.2f}%')
    return classes

def train_test_split(matrix, p):
    np.random.shuffle(matrix)
    train = matrix[0:int(p * len(matrix))]
    test = matrix[int(p*len(matrix)) - 1 : -1]
    return (train, test)

iris = np.column_stack((iris_features, iris_target))
train, test = train_test_split(iris, 0.7)

_ = knn(train, test, 3)

Error = 2.22%


4) Implemente um classificador de distância mínima na linguagem de sua preferência.

In [16]:
def minimum_distance(train, test, d):
    classes_number = len(set(train[:, -1]))
    correct = 0
    classes = []
    
    centroids = np.array([np.mean(train[np.where(train[:, -1] == i)], axis = 0) for i in range(classes_number)])
    
    for i, element in enumerate(test):
        predicted_class = np.argmin(np.array([d(element[0:-1], center[0:-1]) for center in centroids]))
        classes.append(predicted_class)
        
        # print(f'> Prediction = {predicted_class}, Actual = {element[-1]}')
        
        if predicted_class == element[-1]: correct += 1
            
    print(f'Error = {(1 - correct/len(test))*100:.2f}%')
    return classes
    
euclidean = lambda a, b: np.linalg.norm(a-b)

def mahalanobis(a, b):
    ab_cov = cov_matrix(np.array([a, b]))
    return (a - b).dot(ab_cov).dot((a - b).T)

train, test = train_test_split(iris, 0.7)
_ = minimum_distance(train, test, mahalanobis)

Error = 4.44%


5) Implemente uma função discriminante utilizando o log da probabilidade a posteriori para cada uma das classes da base de dados Iris.

6) Implemente um classificador bayesiano para a base de dados Iris.

7) Implemente um classificador bayesiano para a base de dados Iris projetada sobre as duas maiores componentes principais.

8) Determine o erro percentual e o desvio padrão do erro(quando for possível) nos conjuntos de treinamento e validação dos classificadores implementados nas questões 3,4, 6 e 7 utilizando os seguintes métodos de particionamento de dados:
<br />
a) Houldout com 90% das amostras para treinamento e 10% para validação;
<br />
b) Cross-Validation 10-folds;
<br />
c) Monte Carlo Cross-Validation com 90% das amostras para treinamento e 10% para validação;


9) Repita as avaliações da questão 6, calculando a matriz de confusão do erro percentual para cada um dos métodos de particionamento (Houldout, Cross-Validation 10-folds, Monte Carlo Cross-Validation).