In [1]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

<center>
    
# Aprendizagem de Máquina (ES456/2018-2)
## Lista de exercícios 1
### 2018-09-22
    
</center>

1) Utilizando a base de dados Iris, disponível no link abaixo, e a linguagem de programação de sua preferência, calcule para cada classe:
<br />
a) O vetor médio
<br />
b) O vetor de desvio padrão para cada característica da base de dados
<br />
c) O vetor máximo para cada característica da base de dados
<br />
d) O vetor mínimo para cada característica da base de dados
<br />
e) A matriz de dispersão
<br />
f) A matriz de covariância
<br />
g) A matriz de correlação
<br />
h) As duas componentes principais de maior magnitude dos dados
<br />
i) A projeção dos dados nas duas maiores componentes principais

In [2]:
# iris-setosa -> 0
# iris-versicolor -> 1
# iris-virginica -> 2

iris = datasets.load_iris()
iris_features = iris.data[:, :4]
iris_target = iris.target
classes_number = len(set(iris_target))

def class_name(class_):
    if class_ == 0: return 'iris-setosa'
    if class_ == 1: return 'iris-versicolor'
    if class_ == 2: return 'iris-virginica'

def print_answer(question, answer):
    print(f"Resposta {question}:\n{answer}")

In [3]:
def mean(array):
    return sum(array)/len(array)

def column_vec(func, matrix):
    return [func(matrix[:,i]) for i in range(len(matrix[0]))]

print('1a)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(mean, iris_features[np.where(iris_target == i)]))

1a)
iris-setosa
[5.005999999999999, 3.4180000000000006, 1.464, 0.2439999999999999]
iris-versicolor
[5.936, 2.7700000000000005, 4.26, 1.3259999999999998]
iris-virginica
[6.587999999999998, 2.9739999999999998, 5.552, 2.026]


In [4]:
def standard_deviation(array):
    if len(array) == 0: return 0.0
    _mean = mean(array)
    sq_diff_sum = sum([(number-_mean)**2 for number in array])
    return (sq_diff_sum/(len(array)-1))**0.5

print('1b)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(standard_deviation, iris_features[np.where(iris_target == i)]))

1b)
iris-setosa
[0.3524896872134512, 0.38102439795469095, 0.1735111594364455, 0.10720950308167837]
iris-versicolor
[0.5161711470638635, 0.3137983233784114, 0.46991097723995806, 0.197752680004544]
iris-virginica
[0.635879593274432, 0.3224966381726376, 0.5518946956639835, 0.27465005563666733]


In [5]:
print('1c)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(max, iris_features[np.where(iris_target == i)]))

1c)
iris-setosa
[5.8, 4.4, 1.9, 0.6]
iris-versicolor
[7.0, 3.4, 5.1, 1.8]
iris-virginica
[7.9, 3.8, 6.9, 2.5]


In [6]:
print('1d)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(min, iris_features[np.where(iris_target == i)]))

1d)
iris-setosa
[4.3, 2.3, 1.0, 0.1]
iris-versicolor
[4.9, 2.0, 3.0, 1.0]
iris-virginica
[4.9, 2.2, 4.5, 1.4]


In [7]:
def dispersion_matrix(matrix):
    return (matrix - column_vec(mean, matrix)).T.dot((matrix - column_vec(mean, matrix)))

print('1e)')
for i in range(classes_number):
    print(class_name(i))
    print(dispersion_matrix(iris_features[np.where(iris_target == i)]))

1e)
iris-setosa
[[6.0882 4.9146 0.7908 0.5168]
 [4.9146 7.1138 0.5724 0.5604]
 [0.7908 0.5724 1.4752 0.2792]
 [0.5168 0.5604 0.2792 0.5632]]
iris-versicolor
[[13.0552  4.174   8.962   2.7332]
 [ 4.174   4.825   4.05    2.019 ]
 [ 8.962   4.05   10.82    3.582 ]
 [ 2.7332  2.019   3.582   1.9162]]
iris-virginica
[[19.8128  4.5944 14.8612  2.4056]
 [ 4.5944  5.0962  3.4976  2.3338]
 [14.8612  3.4976 14.9248  2.3924]
 [ 2.4056  2.3338  2.3924  3.6962]]


In [8]:
def covariance(x1, x2):
    return mean(x1*x2) - mean(x1)*mean(x2)

def cov_matrix(matrix):
    columns_num = matrix.shape[1]
    result = np.zeros((columns_num, columns_num))
    
    for i in range(columns_num):
        result[i][i] = standard_deviation(matrix[:,i])**2
        for j in range(i+1, columns_num):
            result[i][j] = covariance(matrix[:,i], matrix[:,j])
            result[j][i] = result[i][j]
            
    return result

print('1f)')
for i in range(classes_number):
    print(class_name(i))
    print((cov_matrix(iris_features[np.where(iris_target == i)])))

1f)
iris-setosa
[[0.12424898 0.098292   0.015816   0.010336  ]
 [0.098292   0.14517959 0.011448   0.011208  ]
 [0.015816   0.011448   0.03010612 0.005584  ]
 [0.010336   0.011208   0.005584   0.01149388]]
iris-versicolor
[[0.26643265 0.08348    0.17924    0.054664  ]
 [0.08348    0.09846939 0.081      0.04038   ]
 [0.17924    0.081      0.22081633 0.07164   ]
 [0.054664   0.04038    0.07164    0.03910612]]
iris-virginica
[[0.40434286 0.091888   0.297224   0.048112  ]
 [0.091888   0.10400408 0.069952   0.046676  ]
 [0.297224   0.069952   0.30458776 0.047848  ]
 [0.048112   0.046676   0.047848   0.07543265]]


In [9]:
# alternative method to calculate dispersion matrix
def dispersion_matrix2(matrix):
    return cov_matrix(matrix)*(len(matrix[:, 0])-1)

# alternative method to calculate covariance matrix
def cov_matrix2(matrix):
    return dispersion_matrix2(matrix)/(len(matrix[:, 0]) - 1)

In [10]:
def inverse_std_dev_matrix(matrix):
    columns_num = matrix.shape[1]
    result = np.zeros((columns_num, columns_num))
    
    for i in range(columns_num):
        result[i][i] = 1/(standard_deviation(matrix[:,i])**2)
        for j in range(i+1, columns_num):
            result[i][j] = 1/(standard_deviation(matrix[:,i]) * standard_deviation(matrix[:,j]))
            result[j][i] = result[i][j]
    
    return result
            
def cor_matrix(matrix):
    return cov_matrix(matrix) * inverse_std_dev_matrix(matrix)

print('1g)')
for i in range(classes_number):
    print(class_name(i))
    print(cor_matrix(iris_features[np.where(iris_target == i)]))

1g)
iris-setosa
[[1.         0.73184477 0.25859661 0.27350974]
 [0.73184477 1.         0.17316074 0.27437343]
 [0.25859661 0.17316074 1.         0.30018205]
 [0.27350974 0.27437343 0.30018205 1.        ]]
iris-versicolor
[[1.         0.5153925  0.73896798 0.53553185]
 [0.5153925  1.         0.54931165 0.65071875]
 [0.73896798 0.54931165 1.         0.77093473]
 [0.53553185 0.65071875 0.77093473 1.        ]]
iris-virginica
[[1.         0.44808326 0.84694024 0.27548555]
 [0.44808326 1.         0.39302369 0.52697347]
 [0.84694024 0.39302369 1.         0.31566605]
 [0.27548555 0.52697347 0.31566605 1.        ]]


In [11]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix(iris_features))

print_answer('1h)', eigenvectors[:, 0:2])

Resposta 1h):
[[ 0.36055069 -0.66573651]
 [-0.08199152 -0.7203112 ]
 [ 0.85748176  0.18090193]
 [ 0.35777873  0.07225762]]


In [12]:
print_answer('1i)', iris_features.dot(eigenvectors[:, :2]))

Resposta 1i):
[[ 2.8238684  -5.64863118]
 [ 2.79275402 -5.15532828]
 [ 2.6184974  -5.18433341]
 [ 2.76213784 -5.00954825]
 [ 2.77961417 -5.65408865]
 [ 3.22803727 -6.06775451]
 [ 2.68757008 -5.23650605]
 [ 2.88176066 -5.49193622]
 [ 2.62067783 -4.75042891]
 [ 2.83452517 -5.21649497]
 [ 3.00138347 -5.97432418]
 [ 2.89539869 -5.34069872]
 [ 2.72092108 -5.09598039]
 [ 2.2834012  -4.81738272]
 [ 2.86376176 -6.51098273]
 [ 3.12371036 -6.66381145]
 [ 2.88504456 -6.14011529]
 [ 2.85964627 -5.64140542]
 [ 3.30862375 -6.20267011]
 [ 2.92079699 -5.83940859]
 [ 3.19747728 -5.72205044]
 [ 2.96477401 -5.76015171]
 [ 2.29240119 -5.46015482]
 [ 3.20484485 -5.42862108]
 [ 3.15264322 -5.28642814]
 [ 3.00030544 -5.18572155]
 [ 3.03906458 -5.4593945 ]
 [ 2.94567164 -5.69711464]
 [ 2.86812262 -5.64317372]
 [ 2.87574193 -5.13006283]
 [ 2.91999615 -5.12460536]
 [ 3.09753668 -5.7437793 ]
 [ 2.86069885 -6.13652712]
 [ 2.91069461 -6.41914363]
 [ 2.83452517 -5.21649497]
 [ 2.64091443 -5.40214456]
 [ 2.8823405  

2) Implemente o algoritmo do k-means na linguagem de programação de sua preferência e inicializeeste algoritmo com k=3 centros c1=[5.1,3.5,1.4,0.2], c2=[4.9,3.0,1.4,0.2], c3=[4.7,3.2,1.3,0.2].
<br />
    a) Após a convergência, qual o valor dos centros?
    <br />
    b) Qual o centro mais próximo do centro da classe “Iris-setosa”
    <br />
    c) Qual o centro mais próximo do centro da classe “Iris-versicolor”
    <br />
    d) Qual o centro mais próximo do centro da classe “Iris-virginica”

In [13]:
def dist(a, b):
    return np.linalg.norm(np.array(a) - np.array(b), axis=1)

def kmeans(matrix, k, centroids):
    current_centroids = np.array(centroids)
    previous_centroids = np.zeros(current_centroids.shape)

    error = dist(current_centroids, previous_centroids)
    nearest_clusters = np.zeros(len(matrix))
    
    while sum(error) != 0:
        for i in range(len(matrix)):
            distances = dist(matrix[i], current_centroids)
            nearest_clusters[i] = np.argmin(distances)

            previous_centroids = current_centroids.copy()

        for i in range(k):
            current_centroids[i] = np.mean(matrix[np.where(nearest_clusters == i)], axis=0)

        error = dist(current_centroids, previous_centroids)
    return (nearest_clusters, current_centroids)

def get_center(features, target):
    target_set = set(target)
    return np.array([np.mean(features[np.where(target == i)], 0) for i in range(len(target_set))])

center1 = [5.1, 3.5, 1.4, 0.2]
center2 = [4.9, 3.0, 1.4, 0.2]
center3 = [4.7, 3.2, 1.3, 0.2]

closest_cluster, kmeans_centers = kmeans(iris_features, 3, [center1, center2, center3])

centers = get_center(iris_features, iris_target)

print_answer('2a)', kmeans_centers)

print_answer('2b)', np.argmin(dist(centers[0], kmeans_centers)))
print_answer('2c)', np.argmin(dist(centers[1], kmeans_centers)))
print_answer('2d)', np.argmin(dist(centers[2], kmeans_centers)))

Resposta 2a):
[[6.85384615 3.07692308 5.71538462 2.05384615]
 [5.88360656 2.74098361 4.38852459 1.43442623]
 [5.006      3.418      1.464      0.244     ]]
Resposta 2b):
2
Resposta 2c):
1
Resposta 2d):
0


In [14]:
kmeans_class = closest_cluster.copy()
kmeans_class[np.where(closest_cluster == 2)] = 0
kmeans_class[np.where(closest_cluster == 1)] = 1
kmeans_class[np.where(closest_cluster == 0)] = 2

error = sum([1 if iris_target[i] != kmeans_class[i] else 0 for i in range(len(iris_target))])/len(iris_target)

print(f'Error: {error*100}%')

Error: 11.333333333333332%


3) Implemente o algoritmo do KNN na linguagem de programação de sua preferência.

In [15]:
import collections

def get_neighbors(matrix, element, k):
    dist = lambda a, b: np.linalg.norm(a-b, axis=0)
    near_elements = []
    
    for i, other_element in enumerate(matrix):
        distance = dist(element[0:-1], other_element[0:-1])
        near_elements.append((other_element[-1], distance))
    
    near_elements.sort(key = lambda x: x[1])
    
    # return distances removing 1st element that is the element itself
    return np.array([near_elements[i][0] for i in range(1, k+1)])

def class_from_neighbors(neighbors):
    return max(collections.Counter(neighbors))

def knn(train, test, k):
    classes = []
    correct = 0
    for i, element in enumerate(test):
        neighbors = get_neighbors(train, element, k)
        class_ = class_from_neighbors(neighbors)
        classes.append(class_)
        # print(f'> Prediction = {class_}, Actual = {element[-1]}')
        
        if class_ == element[-1]: correct += 1
            
    print(f'Error = {(1 - correct/len(test))*100}%')
#     print(f'correct = {correct}')
    return classes

def train_test_split(matrix, p):
    np.random.shuffle(matrix)
    train = matrix[0:int(p * len(matrix))]
    test = matrix[int(p*len(matrix)) - 1 : -1]
    return (train, test)

iris = np.column_stack((iris_features, iris_target))
train, test = train_test_split(iris, 0.7)

_ = knn(train, test, 3)

Error = 2.2222222222222254%


4) Implemente um classificador de distância mínima na linguagem de sua preferência.

5) Implemente uma função discriminante utilizando o log da probabilidade a posteriori para cada uma das classes da base de dados Iris.

6) Implemente um classificador bayesiano para a base de dados Iris.

7) Implemente um classificador bayesiano para a base de dados Iris projetada sobre as duas maiores componentes principais.

8) Determine o erro percentual e o desvio padrão do erro(quando for possível) nos conjuntos de treinamento e validação dos classificadores implementados nas questões 3,4, 6 e 7 utilizando os seguintes métodos de particionamento de dados:
<br />
a) Houldout com 90% das amostras para treinamento e 10% para validação;
<br />
b) Cross-Validation 10-folds;
<br />
c) Monte Carlo Cross-Validation com 90% das amostras para treinamento e 10% para validação;


9) Repita as avaliações da questão 6, calculando a matriz de confusão do erro percentual para cada um dos métodos de particionamento (Houldout, Cross-Validation 10-folds, Monte Carlo Cross-Validation).