In [1]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

np.set_printoptions(precision=4)

<center>
    
# Aprendizagem de Máquina (ES456/2018-2)
## Lista de exercícios 1
### 2018-09-22
    
</center>

1) Utilizando a base de dados Iris, disponível no link abaixo, e a linguagem de programação de sua preferência, calcule para cada classe:
<br />
a) O vetor médio
<br />
b) O vetor de desvio padrão para cada característica da base de dados
<br />
c) O vetor máximo para cada característica da base de dados
<br />
d) O vetor mínimo para cada característica da base de dados
<br />
e) A matriz de dispersão
<br />
f) A matriz de covariância
<br />
g) A matriz de correlação
<br />
h) As duas componentes principais de maior magnitude dos dados
<br />
i) A projeção dos dados nas duas maiores componentes principais

In [2]:
# iris-setosa -> 0
# iris-versicolor -> 1
# iris-virginica -> 2

iris = datasets.load_iris()
iris_features = iris.data[:, :4]
iris_target = iris.target
classes_number = len(set(iris_target))

def class_name(class_):
    if class_ == 0: return 'iris-setosa'
    if class_ == 1: return 'iris-versicolor'
    if class_ == 2: return 'iris-virginica'

def print_answer(question, answer):
    print(f"Resposta {question}:\n{answer}")

In [3]:
def mean(array):
    return sum(array)/len(array)

def column_vec(func, matrix):
    return [func(matrix[:,i]) for i in range(len(matrix[0]))]

print('1a)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(mean, iris_features[np.where(iris_target == i)]))

1a)
iris-setosa
[5.005999999999999, 3.4180000000000006, 1.464, 0.2439999999999999]
iris-versicolor
[5.936, 2.7700000000000005, 4.26, 1.3259999999999998]
iris-virginica
[6.587999999999998, 2.9739999999999998, 5.552, 2.026]


In [4]:
def standard_deviation(array):
    if len(array) == 0: return 0.0
    _mean = mean(array)
    sq_diff_sum = sum([(number-_mean)**2 for number in array])
    return (sq_diff_sum/(len(array)-1))**0.5

print('1b)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(standard_deviation, iris_features[np.where(iris_target == i)]))

1b)
iris-setosa
[0.3524896872134512, 0.38102439795469095, 0.1735111594364455, 0.10720950308167837]
iris-versicolor
[0.5161711470638635, 0.3137983233784114, 0.46991097723995806, 0.197752680004544]
iris-virginica
[0.635879593274432, 0.3224966381726376, 0.5518946956639835, 0.27465005563666733]


In [5]:
print('1c)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(max, iris_features[np.where(iris_target == i)]))

1c)
iris-setosa
[5.8, 4.4, 1.9, 0.6]
iris-versicolor
[7.0, 3.4, 5.1, 1.8]
iris-virginica
[7.9, 3.8, 6.9, 2.5]


In [6]:
print('1d)')
for i in range(classes_number):
    print(class_name(i))
    print(column_vec(min, iris_features[np.where(iris_target == i)]))

1d)
iris-setosa
[4.3, 2.3, 1.0, 0.1]
iris-versicolor
[4.9, 2.0, 3.0, 1.0]
iris-virginica
[4.9, 2.2, 4.5, 1.4]


In [7]:
def dispersion_matrix(matrix):
    return (matrix - column_vec(mean, matrix)).T.dot((matrix - column_vec(mean, matrix)))

print('1e)')
for i in range(classes_number):
    print(class_name(i))
    print(dispersion_matrix(iris_features[np.where(iris_target == i)]))

1e)
iris-setosa
[[6.0882 4.9146 0.7908 0.5168]
 [4.9146 7.1138 0.5724 0.5604]
 [0.7908 0.5724 1.4752 0.2792]
 [0.5168 0.5604 0.2792 0.5632]]
iris-versicolor
[[13.0552  4.174   8.962   2.7332]
 [ 4.174   4.825   4.05    2.019 ]
 [ 8.962   4.05   10.82    3.582 ]
 [ 2.7332  2.019   3.582   1.9162]]
iris-virginica
[[19.8128  4.5944 14.8612  2.4056]
 [ 4.5944  5.0962  3.4976  2.3338]
 [14.8612  3.4976 14.9248  2.3924]
 [ 2.4056  2.3338  2.3924  3.6962]]


In [8]:
def covariance(x1, x2):
    return mean(x1*x2) - mean(x1)*mean(x2)

def cov_matrix(matrix):
    return dispersion_matrix(matrix)/(len(matrix[:, 0]) - 1)

print('1f)')
for i in range(classes_number):
    print(class_name(i))
    print((cov_matrix(iris_features[np.where(iris_target == i)])))

1f)
iris-setosa
[[0.1242 0.1003 0.0161 0.0105]
 [0.1003 0.1452 0.0117 0.0114]
 [0.0161 0.0117 0.0301 0.0057]
 [0.0105 0.0114 0.0057 0.0115]]
iris-versicolor
[[0.2664 0.0852 0.1829 0.0558]
 [0.0852 0.0985 0.0827 0.0412]
 [0.1829 0.0827 0.2208 0.0731]
 [0.0558 0.0412 0.0731 0.0391]]
iris-virginica
[[0.4043 0.0938 0.3033 0.0491]
 [0.0938 0.104  0.0714 0.0476]
 [0.3033 0.0714 0.3046 0.0488]
 [0.0491 0.0476 0.0488 0.0754]]


In [9]:
# alternative method to calculate dispersion matrix
def dispersion_matrix2(matrix):
    return cov_matrix(matrix)*(len(matrix[:, 0])-1)

# alternative method to calculate covariance matrix
def covariance(x1, x2):
    return mean(x1*x2) - mean(x1)*mean(x2)

def cov_matrix2(matrix):
    columns_num = matrix.shape[1]
    result = np.zeros((columns_num, columns_num))
    
    for i in range(columns_num):
        for j in range(i, columns_num):
            result[i][j] = covariance(matrix[:,i], matrix[:,j])
            result[j][i] = result[i][j]
            
    return result

In [10]:
def inverse_std_dev_matrix(matrix):
    columns_num = matrix.shape[1]
    result = np.zeros((columns_num, columns_num))
    
    for i in range(columns_num):
        result[i][i] = 1/(standard_deviation(matrix[:,i])**2)
        for j in range(i+1, columns_num):
            result[i][j] = 1/(standard_deviation(matrix[:,i]) * standard_deviation(matrix[:,j]))
            result[j][i] = result[i][j]
    
    return result
            
def cor_matrix(matrix):
    return cov_matrix(matrix) * inverse_std_dev_matrix(matrix)

print('1g)')
for i in range(classes_number):
    print(class_name(i))
    print(cor_matrix(iris_features[np.where(iris_target == i)]))

1g)
iris-setosa
[[1.     0.7468 0.2639 0.2791]
 [0.7468 1.     0.1767 0.28  ]
 [0.2639 0.1767 1.     0.3063]
 [0.2791 0.28   0.3063 1.    ]]
iris-versicolor
[[1.     0.5259 0.754  0.5465]
 [0.5259 1.     0.5605 0.664 ]
 [0.754  0.5605 1.     0.7867]
 [0.5465 0.664  0.7867 1.    ]]
iris-virginica
[[1.     0.4572 0.8642 0.2811]
 [0.4572 1.     0.401  0.5377]
 [0.8642 0.401  1.     0.3221]
 [0.2811 0.5377 0.3221 1.    ]]


In [11]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix(iris_features))

print_answer('1h)', eigenvectors[:, 0:2])

Resposta 1h):
[[ 0.3616 -0.6565]
 [-0.0823 -0.7297]
 [ 0.8566  0.1758]
 [ 0.3588  0.0747]]


In [12]:
print_answer('1i)', iris_features.dot(eigenvectors[:, :2]))

Resposta 1i):
[[ 2.8271 -5.6413]
 [ 2.796  -5.1452]
 [ 2.6215 -5.1774]
 [ 2.7649 -5.0036]
 [ 2.7828 -5.6486]
 [ 3.2314 -6.0625]
 [ 2.6905 -5.2326]
 [ 2.8849 -5.4851]
 [ 2.6234 -4.7439]
 [ 2.8375 -5.208 ]
 [ 3.0048 -5.9667]
 [ 2.8982 -5.3362]
 [ 2.7239 -5.087 ]
 [ 2.2861 -4.8114]
 [ 2.8678 -6.5009]
 [ 3.1275 -6.6595]
 [ 2.8888 -6.1328]
 [ 2.863  -5.6339]
 [ 3.3123 -6.194 ]
 [ 2.924  -5.8352]
 [ 3.2008 -5.7126]
 [ 2.9681 -5.7548]
 [ 2.2955 -5.4563]
 [ 3.2082 -5.4202]
 [ 3.1552 -5.2835]
 [ 3.0034 -5.1757]
 [ 3.0423 -5.4526]
 [ 2.949  -5.6894]
 [ 2.8715 -5.634 ]
 [ 2.8785 -5.1246]
 [ 2.9229 -5.1173]
 [ 3.1013 -5.7328]
 [ 2.8637 -6.1347]
 [ 2.9142 -6.4147]
 [ 2.8375 -5.208 ]
 [ 2.6443 -5.3919]
 [ 2.8861 -5.9215]
 [ 2.8375 -5.208 ]
 [ 2.5295 -4.8345]
 [ 2.921  -5.5508]
 [ 2.7412 -5.5858]
 [ 2.6591 -4.3819]
 [ 2.513  -4.9804]
 [ 3.1058 -5.5106]
 [ 3.3025 -5.7574]
 [ 2.7957 -5.072 ]
 [ 2.9738 -5.8251]
 [ 2.671  -5.0941]
 [ 2.9687 -5.901 ]
 [ 2.8074 -5.4297]
 [ 6.7961 -6.0002]
 [ 6.4438 -5.6339

2) Implemente o algoritmo do k-means na linguagem de programação de sua preferência e inicializeeste algoritmo com k=3 centros c1=[5.1,3.5,1.4,0.2], c2=[4.9,3.0,1.4,0.2], c3=[4.7,3.2,1.3,0.2].
<br />
    a) Após a convergência, qual o valor dos centros?
    <br />
    b) Qual o centro mais próximo do centro da classe “Iris-setosa”
    <br />
    c) Qual o centro mais próximo do centro da classe “Iris-versicolor”
    <br />
    d) Qual o centro mais próximo do centro da classe “Iris-virginica”

In [13]:
def dist(a, b):
    return np.linalg.norm(np.array(a) - np.array(b), axis=1)

def kmeans(matrix, k, centroids):
    current_centroids = np.array(centroids)
    previous_centroids = np.zeros(current_centroids.shape)

    error = dist(current_centroids, previous_centroids)
    nearest_clusters = np.zeros(len(matrix))
    
    while sum(error) != 0:
        for i in range(len(matrix)):
            distances = dist(matrix[i], current_centroids)
            nearest_clusters[i] = np.argmin(distances)

            previous_centroids = current_centroids.copy()

        for i in range(k):
            current_centroids[i] = np.mean(matrix[np.where(nearest_clusters == i)], axis=0)

        error = dist(current_centroids, previous_centroids)
    return (nearest_clusters, current_centroids)

def get_center(features, target):
    target_set = set(target)
    return np.array([np.mean(features[np.where(target == i)], 0) for i in range(len(target_set))])

center1 = [5.1, 3.5, 1.4, 0.2]
center2 = [4.9, 3.0, 1.4, 0.2]
center3 = [4.7, 3.2, 1.3, 0.2]

closest_cluster, kmeans_centers = kmeans(iris_features, 3, [center1, center2, center3])

centers = get_center(iris_features, iris_target)

print_answer('2a)', kmeans_centers)

print_answer('2b)', np.argmin(dist(centers[0], kmeans_centers)))
print_answer('2c)', np.argmin(dist(centers[1], kmeans_centers)))
print_answer('2d)', np.argmin(dist(centers[2], kmeans_centers)))

Resposta 2a):
[[6.8538 3.0769 5.7154 2.0538]
 [5.8836 2.741  4.3885 1.4344]
 [5.006  3.418  1.464  0.244 ]]
Resposta 2b):
2
Resposta 2c):
1
Resposta 2d):
0


In [14]:
kmeans_class = closest_cluster.copy()
kmeans_class[np.where(closest_cluster == 2)] = 0
kmeans_class[np.where(closest_cluster == 1)] = 1
kmeans_class[np.where(closest_cluster == 0)] = 2

error = sum([1 if iris_target[i] != kmeans_class[i] else 0 for i in range(len(iris_target))])/len(iris_target)

print(f'Error: {error*100:.2f}%')

Error: 11.33%


3) Implemente o algoritmo do KNN na linguagem de programação de sua preferência.

In [15]:
import collections

def get_neighbors(matrix, element, k):
    dist = lambda a, b: np.linalg.norm(a-b, axis=0)
    near_elements = []
    
    for i, other_element in enumerate(matrix):
        distance = dist(element[0:-1], other_element[0:-1])
        near_elements.append((other_element[-1], distance))
    
    near_elements.sort(key = lambda x: x[1])
    
    # return distances removing 1st element that is the element itself
    return np.array([near_elements[i][0] for i in range(1, k+1)])

def class_from_neighbors(neighbors):
    return max(collections.Counter(neighbors))

def knn(train, test, k):
    classes = []
    correct = 0
    for i, element in enumerate(test):
        neighbors = get_neighbors(train, element, k)
        class_ = class_from_neighbors(neighbors)
        classes.append(class_)
        # print(f'> Prediction = {class_}, Actual = {element[-1]}')
        
        if class_ == element[-1]: correct += 1
    
    error = 1 - correct/len(test)
    # print(f'Error = {error*100:.2f}%')
    return classes, error

def train_test_split(matrix, p):
    np.random.shuffle(matrix)
    train = matrix[0:int(p * len(matrix))]
    test = matrix[int(p*len(matrix)) - 1 : -1]
    return (train, test)

iris = np.column_stack((iris_features, iris_target))
train, test = train_test_split(iris, 0.7)

_ = knn(train, test, 3)

4) Implemente um classificador de distância mínima na linguagem de sua preferência.

In [16]:
def minimum_distance(train, test, d):
    classes_number = len(set(train[:, -1]))
    correct = 0
    classes = []
    
    centroids = np.array([np.mean(train[np.where(train[:, -1] == i)], axis = 0) for i in range(classes_number)])
    
    for i, element in enumerate(test):
        predicted_class = np.argmin(np.array([d(element[0:-1], center[0:-1]) for center in centroids]))
        classes.append(predicted_class)
        
        # print(f'> Prediction = {predicted_class}, Actual = {element[-1]}')
        
        if predicted_class == element[-1]: correct += 1
    
    error = 1 - (correct/len(test))
    # print(f'Error = {error*100:.2f}%')
    return classes, error
    
euclidean = lambda a, b: np.linalg.norm(a-b)

def mahalanobis(a, b):
    ab_cov = cov_matrix(np.array([a, b]))
    return (a - b).dot(ab_cov).dot((a - b).T)

train, test = train_test_split(iris, 0.7)
_ = minimum_distance(train, test, mahalanobis)

5) Implemente uma função discriminante utilizando o log da probabilidade a posteriori para cada uma das classes da base de dados Iris.

<center>
    $g_i(x) = -\frac{1}{2}(\mathbf{x}-\mathbf{\mu_i})^T \mathbf{\Sigma_i^{-1}}(\mathbf{x}-\mathbf{\mu_i})- \frac{d}{2}ln(2\pi)-\frac{1}{2}ln(\left | \mathbf{\Sigma_i} \right |) + ln(P(\omega_i))$
    </center>
    <br />Simplificando a função discriminante: <br />
    <center>
    $g_i(x) = (\mathbf{x}-\mathbf{\mu_i})^T \mathbf{\Sigma_i^{-1}}(\mathbf{x}-\mathbf{\mu_i}) +ln(\left | \mathbf{\Sigma_i} \right |) - 2ln(P(\omega_i))$
    </center>

In [17]:
def discriminant(element, mean, cov, w_i):
    inv_cov = np.linalg.inv(cov)
    determinant_cov = np.linalg.det(cov)
    return (element-mean).dot(inv_cov).dot((element-mean).T) + np.log(determinant_cov) - 2*np.log(w_i)

6) Implemente um classificador bayesiano para a base de dados Iris.

In [18]:
def baysian_classifier(train, test):
    classes_number = len(set(train[:, -1]))
    result = np.zeros((len(test), classes_number))
    
    for i in range(classes_number):
        selected_train = train[np.where(train[:, -1] == i)]
        mean = np.mean(selected_train[:, 0:-1], axis = 0)
        cov = cov_matrix(selected_train[:, 0:-1])
        w_i = len(selected_train)/len(train)
        
        for j, element in enumerate(test):
            element = element[0:-1]
            result[j][i] = discriminant(element, mean, cov, w_i)
    
    result = np.argmin(result, axis=1)
    error = sum([1 if test[i, -1] != result[i] else 0 for i in range(len(test))])/len(test)
    # print(f'Error = {error*100:.2f}%')
    return result, error

train, test = train_test_split(iris, 0.7)
result, error = baysian_classifier(train, test)

7) Implemente um classificador bayesiano para a base de dados Iris projetada sobre as duas maiores componentes principais.

In [19]:
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix(iris_features))
iris_feat_pca = iris_features.dot(eigenvectors[:, 0:2])
iris_pca = np.column_stack((iris_feat_pca, iris_target))

train, test = train_test_split(iris_pca, 0.7)
result, error = baysian_classifier(train, test)

8) Determine o erro percentual e o desvio padrão do erro(quando for possível) nos conjuntos de treinamento e validação dos classificadores implementados nas questões 3,4, 6 e 7 utilizando os seguintes métodos de particionamento de dados:
<br />
a) Houldout com 90% das amostras para treinamento e 10% para validação;


In [20]:
train, test = train_test_split(iris, 0.9)
train_pca, test_pca = train_test_split(iris_pca, 0.9)

_, knn_error = knn(train, test, 3)
_, mind_error = minimum_distance(train, test, euclidean)
_, baysian_error = baysian_classifier(train, test)
_, baysian_pca_error = baysian_classifier(train_pca, test_pca)

print(f'KNN Error = {knn_error*100:.2f}%')
print(f'Minimum Distance Error = {mind_error*100:.2f}%')
print(f'Baysian Error = {baysian_error*100:.2f}%')
print(f'Baysian PCA Error = {baysian_pca_error*100:.2f}%')

KNN Error = 6.67%
Minimum Distance Error = 6.67%
Baysian Error = 0.00%
Baysian PCA Error = 6.67%


b) Cross-Validation 10-folds;

In [21]:
def kfolds_split(matrix, k):
    np.random.shuffle(matrix)
    folds = []
    
    for i in range(k):
        lowerbound = int((len(matrix)/k) * i)
        upperbound = int((len(matrix)/k) * (i+1))
        folds.append(matrix[lowerbound:upperbound,:])
    
    return folds

def kfolds_validation(matrix, k, validation):
    folds = kfolds_split(matrix, k)
    error = []
    
    for i in range(k):
        folds_copy = folds.copy()
        test = folds_copy.pop(i)
        train = np.row_stack(folds_copy)
        
        if validation == 0:
            error = np.append(error, knn(train, test, 3)[1])
        elif validation == 1:
            error = np.append(error, [minimum_distance(train, test, euclidean)[1]])
        elif validation == 2:
            error = np.append(error, [baysian_classifier(train, test)[1]])
    return np.mean(error), np.std(error)


print(f'KNN Error = {kfolds_validation(iris, 10, 0)}')
print(f'Minimum Distance Error = {kfolds_validation(iris, 10, 1)}')
print(f'Baysian Error = {kfolds_validation(iris, 10, 2)}')
print(f'Baysian PCA Error = {kfolds_validation(iris_pca, 10, 2)}')

KNN Error = (0.05333333333333332, 0.04988876515698588)
Minimum Distance Error = (0.07999999999999999, 0.08326663997864532)
Baysian Error = (0.026666666666666665, 0.03265986323710904)
Baysian PCA Error = (0.026666666666666665, 0.044221663871405324)


c) Monte Carlo Cross-Validation com 90% das amostras para treinamento e 10% para validação;

In [22]:
def monte_carlo_cv(matrix, p, k, validation):
    error = np.array([])
    for i in range(k):
        train, test = train_test_split(iris_pca, p) 
        
        if validation == 0:
            error = np.append(error, knn(train, test, 3)[1])
        elif validation == 1:
            error = np.append(error, [minimum_distance(train, test, euclidean)[1]])
        elif validation == 2:
            error = np.append(error, [baysian_classifier(train, test)[1]])
    return np.mean(error), np.std(error)

print(f'KNN Error = {monte_carlo_cv(iris, 0.7, 100, 0)}')
print(f'Minimum Distance Error = {monte_carlo_cv(iris, 0.9, 100, 1)}')
print(f'Baysian Error = {monte_carlo_cv(iris, 0.9, 100, 2)}')
print(f'Baysian PCA Error = {monte_carlo_cv(iris_pca, 0.9, 100, 2)}')

KNN Error = (0.05466666666666665, 0.03021241670996861)
Minimum Distance Error = (0.08133333333333331, 0.06638607618402453)
Baysian Error = (0.034, 0.04054626986542658)
Baysian PCA Error = (0.034, 0.04054626986542658)


9) Repita as avaliações da questão 6, calculando a matriz de confusão do erro percentual para cada um dos métodos de particionamento (Houldout, Cross-Validation 10-folds, Monte Carlo Cross-Validation).

In [49]:
def confusion_matrix(predicted, actual):
    conf_shape = len(set(actual))
    conf = np.zeros((conf_shape, conf_shape))
    for pred, act in zip(predicted, actual):
        conf[int(act), int(pred)] += 1
    return conf/conf.sum() * 100
    
train, test = train_test_split(iris, 0.9)
train_pca, test_pca = train_test_split(iris_pca, 0.9)
test_labels = test[:, -1]
test_pca_labels = test_pca[:, -1]

knn_predicted, _ = knn(train, test, 3)
mind_predicted, _ = minimum_distance(train, test, euclidean)
baysian_predicted, _ = baysian_classifier(train, test)
baysian_pca_predicted, _ = baysian_classifier(train_pca, test_pca)

print(f'KNN Confusion Matrix\n{confusion_matrix(knn_predicted, test_labels)}\n')
print(f'Minimum Confusion Matrix\n{confusion_matrix(mind_predicted, test_labels)}\n')
print(f'Baysian Confusion Matrix\n{confusion_matrix(baysian_predicted, test_labels)}\n')
print(f'Baysian  PCA Confusion Matrix\n{confusion_matrix(baysian_pca_predicted, test_pca_labels)}\n')

KNN Confusion Matrix
[[20.      0.      0.    ]
 [ 0.     33.3333  0.    ]
 [ 0.      6.6667 40.    ]]

Minimum Confusion Matrix
[[20.      0.      0.    ]
 [ 0.     33.3333  0.    ]
 [ 0.     13.3333 33.3333]]

Baysian Confusion Matrix
[[20.      0.      0.    ]
 [ 0.     33.3333  0.    ]
 [ 0.      0.     46.6667]]

Baysian  PCA Confusion Matrix
[[46.6667  0.      0.    ]
 [ 0.     20.      0.    ]
 [ 0.      0.     33.3333]]



In [ ]:
# https://onlinecourses.science.psu.edu/stat505/node/94/
# https://people.revoledu.com/kardi/tutorial/LDA/Numerical%20Example.html

def linear_discriminant(matrix, test):
    matrix_features = matrix[:,0:-1]
    columns_num = matrix_features.shape[1]
    classes = set(matrix[:,-1])
    pooled_covariance = np.zeros((columns_num, columns_num))
    
    for class_ in classes:
        matrix_class = matrix_features[np.where(matrix[:, -1] == class_)]
        p = len(matrix_class)/len(matrix)
        corrected_data = matrix_class - np.mean(matrix_features, axis=0)
        pooled_covariance += corrected_data.T.dot(corrected_data) / (len(corrected_data) - 1)
        
    pc_inv = np.linalg.inv(pooled_covariance)
    classification = []
    correct = 0
    
    for i, element in enumerate(test):
        discriminants = []
        for class_ in classes:
            matrix_class = matrix_features[np.where(matrix[:, -1] == class_)]
            class_mean = np.mean(matrix_class, axis=0)
            
            element_features = element[0:-1]
            
            p = len(matrix_class)/len(matrix)
            
            f_i = class_mean.dot(pc_inv).dot(element_features.T) - 0.5*class_mean.dot(pc_inv).dot(class_mean.T) + np.log(p)
            discriminants.append(f_i)
        classification.append(np.argmax(discriminants))
        
        if classification[i] == element[-1]: correct += 1
        print(f'> Prediction = {classification[i]}, Actual = {element[-1]}')
        
    print(f'Error = {(1 - correct/len(test))*100:.2f}%')
    
    return classification
        
# train, test = train_test_split(iris, 0.7)
# _ = linear_discriminant(train, test)